Add the config changes to handle CHT communication with the mediator
medic/cht-interoperability pull request #16
Opened 2023-01-24 15:41 UTC by njogz

# Description

This adds the relevant config changes required for the CHT to handle communication with the mediator for the loss to followup workflow.

Closes medic/interoperability#13

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.
 
# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

2023-01-27 09:16 UTC, samuelimoisili requested changes

2023-01-27 09:16 UTC, samuelimoisili commented on cht-config/app_settings.json
> +        "gender": "doc.sex",
The mediator is expecting `sex` not `gender`.

2023-01-27 09:16 UTC, samuelimoisili commented on cht-config/app_settings.json
> +        "birthDate": "doc.date_of_birth",
We are expecting `date_of_birth` not `birthDate`. We had a discussion yesterday about data transformation taking place on the mediator and not cht-core.

2023-01-27 09:16 UTC, samuelimoisili commented on cht-config/app_settings.json
> +    "FHIR_practitioner": {
Do we need an issue to create the practitioner endpoint?

2023-01-27 09:16 UTC, samuelimoisili commented on cht-config/app_settings.json
> +        "subject": {
The mediator is expecting `patient_id` instead of subject.

2023-02-13 10:32 UTC, samuelimoisili approved these changes

2023-02-22 15:35 UTC, andrablaj reviewed
@njogz I tried to upload the config locally and bumped into several errors. Please see my comments on the [related issue](https://github.com/medic/interoperability/issues/13#issuecomment-1440266236) and the steps I followed to mitigate the errors.

2023-02-22 15:47 UTC, andrablaj requested changes
Thanks for specifying which files we should pay attention to. 

Sharing some comments about the config upload part and the local setup for now.

2023-02-22 15:47 UTC, andrablaj commented on README.md
> +1. Ensure you have [cht-conf](https://www.npmjs.com/package/cht-conf) installed and Run `cht --local` to compile and upload that configurationto upload the app settings to your local CHT-core instanc
I suggest adding a step for specifying that an instance of CHT should run locally and [the link](https://docs.communityhealthtoolkit.org/apps/tutorials/local-setup/) for the local setup instructions.

2023-02-22 15:47 UTC, andrablaj commented on README.md
> +1. Ensure you have [cht-conf](https://www.npmjs.com/package/cht-conf) installed and Run `cht --local` to compile and upload that configurationto upload the app settings to your local CHT-core instanc
1. Ensure you have [cht-conf](https://www.npmjs.com/package/cht-conf) installed and Run `cht --local` to compile and upload that configurationto upload the app settings to your local CHT-core instance.
```suggestion
1. Ensure you have [cht-conf](https://www.npmjs.com/package/cht-conf) installed and run `cht --local` to compile and upload the app settings configuration to your local CHT instance.
```

2023-02-22 16:07 UTC, lorerod requested changes

2023-02-22 16:07 UTC, lorerod commented on README.md
> +
I suggest adding the steps for the reader to try the CHT communication with the mediator.

2023-02-22 16:07 UTC, lorerod commented on README.md
> +1. Run `npm install` to install the dependencies.
I wasn't able to make this work as per instructions. 
The steps I followed to be able to load the config where:

1. Created a directory outside the interoperability project
2. Copied the content of /interoperability/cht-config to the directory created in 1.
3. Executed cht initialise-project-layout
4. Executed cht --url=[https://user:pass@****.my.local-ip.co](https://medic:****@%2A%2A%2A%2A.my.local-ip.co/) --accept-self-signed-certs

2023-02-22 17:38 UTC, samuelimoisili commented on cht-config/app_settings.json
> +        "base_url": "http://localhost:5001",
We are updating the fhir database without passing through the mediator.

2023-02-22 17:40 UTC, samuelimoisili commented on cht-config/app_settings.json
> +        "path": "/fhir/Encounter",
We are updating FHIR directly without passing through the mediator. Do we want to allow CHT communicate directly FHIR database?

2023-03-02 09:55 UTC, andrablaj commented
Thank you for the updates @njogz! I tested the changes and I confirm that the config was uploaded successfully, without any extra action or file change from my side.

Please address my `README` suggestions above before I can review the PR.

2023-03-03 10:58 UTC, andrablaj approved these changes
Managed to upload the config by following the steps  in the `README`.

A simple way to verify if the config is loaded correctly is to access a URL like `https://*****.my.local-ip.co/#/contacts/someUUID/report/interop_follow_up `and to retrieve correctly the follow up form.

2023-03-03 11:02 UTC, merged