26 create subscription resource
medic/cht-interoperability pull request #28
Opened 2023-01-26 21:38 UTC by njogz

# Description

This PR creates a subscription resource in the FHIR server which makes it easier to inform the requesting service once a follow up task has been completed. It also calls the CHT's API endpoint for submitting a record so as to create a task

Closes #26 

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.
 
# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

2023-02-17 09:07 UTC, samuelimoisili commented on mediator/src/controllers/service-request.ts
> +    const FHIRSubscriptionResource = generateFHIRSubscriptionResource(patientId, callbackURL);
We had a discussion about intercepting the FHIR subscription at Zanzibar. Are we still implementing that?

2023-02-17 10:56 UTC, samuelimoisili commented on mediator/src/controllers/service-request.ts
> +  callbackURL: string;
Yeah, that's for variable names in JavaScript, but this is JSON request. The `app_settings.json` uses snake_case for variable naming in JSON.

2023-02-17 10:56 UTC, samuelimoisili commented on mediator/src/controllers/service-request.ts
> +    const FHIRSubscriptionResource = generateFHIRSubscriptionResource(patientId, callbackURL);
Oh, okay. Should I create an issue for that?

2023-02-17 11:01 UTC, samuelimoisili commented on mediator/src/controllers/service-request.ts
> +    return {status: res.status};
Yeah, that works. Status code gets the job done, but sending a subscription resource to the requesting system will be beneficial in the future if we want the requesting system to track the progress of the task, cancel callbacks, update callback url (maybe the domain was migrated) or cancel the task in the future.

2023-02-17 11:02 UTC, samuelimoisili commented on mediator/src/controllers/service-request.ts
> +    return {status: res.status};
We can discuss about this in the proposed design meeting.

2023-02-20 11:09 UTC, samuelimoisili approved these changes

2023-02-22 16:13 UTC, andrablaj reviewed
@njogz would it be possible to enumerate the steps and give examples of payloads to test this PR? I would like to reproduce the task creation in the CHT. Thank you!

2023-02-23 14:55 UTC, andrablaj requested changes
Sharing an error I bumped in while running the [step-by-step guide](https://github.com/medic/interoperability/issues/26#issuecomment-1441451470) you suggested.

2023-02-23 14:55 UTC, andrablaj commented on mediator/src/middlewares/schemas/service-request.ts
> +  patient_id: joi.number().required(),
@njogz, when posting the patient/callbackURL payload to service-request, as advised in [your step-by-step guide](https://github.com/medic/interoperability/issues/26#issuecomment-1441451470),  I get:

>     "message": "\"patient_id\" must be a number",

and that is normal, as the schema required a number and not a uuid. anything that I am missing here?

2023-03-03 15:34 UTC, andrablaj requested changes
@njogz so happy that I managed to reproduce all the steps in the flow locally, great job on this issue!

My comments are mostly around documentation and style. 

While running the flow locally, I noticed that the logs were not clear enough, I imagine one step to solve this would be #40.

I also noticed the lack of unit testing, and I an not sure if you were considering them via another issue.

2023-03-03 15:34 UTC, andrablaj commented on README.md
> +1. Securely save the `interop-client` user's password to the database using the instructions [here](https://docs.communityhealthtoolkit.org/apps/reference/api/#credentials). Change the values `mykey`
I would add an example of `PUT` request, just to make it extra clear:
`curl -X PUT -H "Content-Type: text/plain" http://medic:password@localhost:5988/api/v1/credentials/openhim1 -d 'interop-password'`

2023-03-03 15:34 UTC, andrablaj commented on README.md
>  1. Set up a proxy to your local CHT instance by running using something like [nginx-local-ip](https://github.com/medic/nginx-local-ip) or [ngrok](https://ngrok.com/) and update the `CHT_URL` value in
> value in the `.env` file with the new URL.

I suggest adding extra step before this step and mentioning the `.env` file creation, and the existence of the `env.template` file.
Mentioning `CHT_USERNAME` & `CHT_PASSWORD` can be helpful too, as the users might use different credentials.

2023-03-03 15:34 UTC, andrablaj commented on mediator/src/controllers/service-request.ts
> +import {FHIR, CHT} from '../../config';
There are some formatting differences, and I assume they would be fixed via #43 ?

2023-03-03 15:34 UTC, andrablaj commented on mediator/src/controllers/service-request.ts
> +      // TODO: delete the subscription
Do we have an issue to tackle this `TODO`? If not, I recommend opening one (+ explaining why we need to delete the subscription). There is no such step in the sequence diagram, and it's worth a discussion on wether we need to delete it or not.

2023-03-06 11:54 UTC, andrablaj approved these changes
This looks good, thank you for the documentation updates @njogz

2023-03-06 11:57 UTC, merged